### PR TITLE
roolback addons.xml.md5

### PR DESCRIPTION
**Pull request by Angelinas1**

### CODE REVIEW

**Comment by jeroenpardon** [comment]
The md5 hash really is correct, go to https://github.com/jeroenpardon/repository.jeroen/blob/master/addons.xml.md5 and click on the "raw" button, even that leads to a 404...the file is right there! :(

**Comment by Angelinas1** [comment]
I see try mine....
https://raw.githubusercontent.com/Angelinas1/repository.jeroen/5ef614dfe8ceea2bce874b72c89e0095903c4e10/addons.xml.md5

**Comment by Angelinas1** [comment]
I change in mine addon.xml for your repo.....working
		<info>https://raw.github.com/angelinas1/repository.jeroen/patch-1/addons.xml</info>
		<checksum>https://raw.github.com/angelinas1/repository.jeroen/patch-1/addons.xml.md5</checksum>
		<datadir zip="true">https://raw.github.com/angelinas1/repository.jeroen/patch-1/</datadir>

**Comment by jeroenpardon** [comment]
still nothing :(

**Comment by Angelinas1** [comment]
https://raw.githubusercontent.com/jeroenpardon/repository.jeroen/9851309f1abe97ecba13fc77b1c11b5035379571/addons.xml.md5
this is ok, how you change this file...
I sugest to use 
https://www.gitkraken.com/download
Create your file on local disc and upload on github with this program

**Comment by jeroenpardon** [comment]
I use Tower, but I don't think my Github client has anything to do with it. The .md5 file I have created in different ways. Either with a script, manually through command line, using an online converter, all with the same resulting hash. Creating the file directly on Github instead of uploading doesn't help either.

**Comment by jeroenpardon** [comment]
Guess what, I set up a repo at gitlab. Worked instantly... I knew I wasn't crazy, Github is messed up.

**Pull request merged**
